name: Febspot Bot Runner

on:
  workflow_dispatch:      # Menambahkan tombol "Run Workflow" manual
  schedule:
    - cron: '*/30 * * * *' # Berjalan otomatis setiap 30 menit

jobs:
  execute-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Ambil Kode dari Repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Library
      run: |
        pip install -r requirements.txt

    - name: Jalankan Bot
      # Parameter -u agar log muncul secara real-time
      run: python -u bot.py
